mutation CreateComment($comment: String!, $deckId: ID, $cardId: ID) {
  createComment(deckId: $deckId, cardId: $cardId, comment: $comment) {
    id
    createdAt
    comment
    card {
      id
      comments {
        id
        createdAt
        comment
        author {
          id
          username
        }
      }
    }
    deck {
      id
      comments {
        id
        createdAt
        comment
        author {
          id
          username
        }
      }
    }
  }
}
