query GetCard($id: ID!) {
  card(id: $id) {
    id
    title
    side
    type
    subType
    imageUrl
    gametext
    comments {
      id
      createdAt
      comment
      author {
        id
        username
      }
    }
  }
}
