query GetRecentDecks {
  recentDecks {
    id
    side
    title
    description
    author {
      username
    }
    createdAt
    averageRating
    cards {
      id
      front {
        type
      }
    }
  }
}
