query GetRecentDecks {
  recentDecks {
    id
    side
    title
    description
    author {
      id
      username
    }
    createdAt
    ratings {
      id
      rating
    }
    deckCards {
      id
      card {
        id
        type
      }
    }
  }
}
