query GetDeck($id: ID!) {
  deck(id: $id) {
    id
    title
    author {
      id
      username
    }
    deckCards {
      id
      isInSideDeck
      card {
        id
        card_id
        side
        rarity
        set
        title
        type
        imageUrl
        subType
        destiny
        power
        deploy
        forfeit
        gametext
        lore
        gemp_card_id
      }
    }
  }
}
