query GetCards {
  cards {
    id
    type
    card_id
    deploy
    destiny
    forfeit
    gametext
    imageUrl
    lore
    power
    rarity
    set
    side
    subType
    title
    gemp_card_id
  }
}
