type Query {
  hello: String!
  recentDecks: [Deck]!
  cards: [Card]!
  deck(id: ID!): Deck!
  decks(authorId: ID): [Deck]!
}
type LoginResponse {
  jwt: String!
}
type SuccessResponse {
  success: Boolean!
}
type DeckCardIDResponse {
  newDeckCardId: ID!
}
input DeckUpdate {
  title: String
  description: String
  published: Boolean
}

type Mutation {
  createDeck(side: Side!): Deck!
  login(username: String!, password: String!): LoginResponse!
  addCardToDeck(deckId: ID!, cardId: ID!): DeckCardIDResponse!
  removeCardFromDeck(deckCardId: ID!): SuccessResponse!
  setStartingCard(deckCardId: ID!, isStartingCard: Boolean!): DeckCard!
  updateDeck(deckId: ID!, updates: DeckUpdate!): Deck!
  createDeckRating(deckId: ID!, rating: Float!): DeckRating!
  createComment(deckId: ID, cardId: ID, comment: String!): Comment!
}

type Comment {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  comment: String!
  author: User!
  card: Card
  deck: Deck
}

enum Side {
  Dark
  Light
}
scalar Date
type DeckRating {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  rating: Float!
  deck: Deck!
}
type Deck {
  id: ID!
  createdAt: Date!
  side: Side!
  title: String!
  published: Boolean!
  description: String!
  author: User!
  ratings: [DeckRating]!
  deckCards: [DeckCard]!
}
type DeckCard {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  card: Card!
  deck: Deck!
  isInSideDeck: Boolean!
  isStartingCard: Boolean!
}
type Card {
  id: ID!
  cardId: String!
  side: Side!
  rarity: String!
  set: String!
  title: String!
  type: String!
  imageUrl: String!
  subType: String
  destiny: String
  power: String
  deploy: String
  forfeit: String
  gametext: String
  lore: String
  gemp_card_id: String
}
type User {
  id: ID!
  username: String!
}
