mutation UpdateDeck(
  $deckId: ID!
  $title: String
  $description: String
  $published: Boolean
) {
  updateDeck(
    deckId: $deckId
    updates: { title: $title, description: $description, published: $published }
  ) {
    id
    title
    description
  }
}
