import { Side } from "../graphql/types";

export const dummyDeckData = [
  {
    id: "1",
    side: Side.Dark,
    title: "May the 4th be with you",
    createdAt: new Date(),
    author: { username: "darthvoodoo" },
    days: 2,
    description: "Fast paced, high stakes, fun deck",
    averageRating: 3.5,
  },
  {
    id: "2",
    side: Side.Light,
    title: "Princess leia's legion",
    createdAt: new Date(),
    author: { username: "freeForce4you" },
    days: 10,
    description: "Slow methodical deck good against many types",
    averageRating: 5,
  },
  {
    id: "3",
    side: Side.Dark,
    title: "PLANET DESTROYER",
    createdAt: new Date(),
    author: { username: "darthWillMaulYou" },
    days: 7,
    description: "Weapons galore",
    averageRating: 2.5,
  },
  {
    id: "4",
    side: Side.Light,
    title: "Solo's surprise",
    createdAt: new Date(),
    author: { username: "Falconator" },
    days: 15,
    description: "Fast paced, high stakes, fun deck",
    averageRating: 4.5,
  },
  {
    id: "5",
    side: Side.Dark,
    title: "Jar Jar's Jam",
    createdAt: new Date(),
    author: { username: "solo547" },
    days: 12,
    description: "Slow methodical deck good against many types",
    averageRating: 3.5,
  },
  {
    id: "6",
    side: Side.Dark,
    title: "Empire",
    createdAt: new Date(),
    author: { username: "Iam Your Father?" },
    days: 1,
    description: "Solid all around deck",
    averageRating: 3,
  },
];
